# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-01-10 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200110_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='ad',
        ),
    ]
